### ISSUE TITLE
Hi there

### ISSUE THREAD

**Issue by astrale-sharp** [QbieShay/VFX#1]
noticed you had a beautiful fire breath work done in godot, would u be willing to share the code at some point? ;)

Love, Ash

**Comment by QbieShay** [comment]
Hey @astrale-sharp, thank you!

There is a breakdown with a couple of textures on realtimeVFX (https://realtimevfx.com/t/qbieshay-sketch-46-dragon-breath)
As for code, there is none really :)

**Comment by astrale-sharp** [comment]
I'm a total beginner so I'm unable to follow the breakdown to a working example project unfortunatly..
